### ISSUE TITLE
Using cplx solver with clingo

### ISSUE THREAD

**Issue by faseehahmad** [potassco/clingoLP#3]
Hello everyone,
I have installed cplex solver and have checked it by importing it in python. It is working fine. I have not installed lpsolve because I don't want to use it. Default solver is cplx. I tried to run the following through command line

clingo clingoLP.py example_encoding.lp example_instance.lp -c show=1

It gives the following error
Import Error: No module named lpsolve

Do I need to install lpsolve to eliminate this error or there is something else wrong?
Thank you

**Comment by schellhorn** [comment]
Hello,
since we provide the possibility to use one of both lp solvers, we need to import their functionality.
If one of both solvers is not installed, then you will get this Import Error.
The easiest way to solve this issue is to remove lines 709 to 866 of clingoLP.py (to remove the wrapper for lpsolve).
Best,
Sebastian

**Comment by faseehahmad** [comment]
Thank you so much
